USE eco_tourism;
CREATE TABLE IF NOT EXISTS categories(category_id INT AUTO_INCREMENT PRIMARY KEY,category_name VARCHAR(100) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS activity_types(activity_type_id INT AUTO_INCREMENT PRIMARY KEY,activity_type_name VARCHAR(100) UNIQUE NOT NULL);
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS category_id INT NULL AFTER image;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS activity_type_id INT NULL AFTER image;
INSERT IGNORE INTO categories(category_name) VALUES ('Heritage'),('Highlands'),('Wildlife'),('Coast');
INSERT IGNORE INTO activity_types(activity_type_name) VALUES ('Wildlife'),('Hiking'),('Culture'),('Wellness'),('Water');
INSERT INTO destinations(name,description,image,category_id,location,highlights,gallery_image1,gallery_image2,gallery_image3,gallery_image4)
SELECT 'Sigiriya','Rise before the crowds and climb the legendary Lion Rock, where frescoes, water gardens and vast jungle views reveal an ancient world.','assets/gallery-1.jpg',(SELECT category_id FROM categories WHERE category_name='Heritage'),'Central Province','Sunrise climb, ancient frescoes, village lunch','assets/gallery-1.jpg','assets/gallery-2.jpg','assets/gallery-3.png','assets/gallery-4.jpg' WHERE NOT EXISTS(SELECT 1 FROM destinations WHERE name='Sigiriya');
INSERT INTO destinations(name,description,image,category_id,location,highlights,gallery_image1,gallery_image2,gallery_image3,gallery_image4)
SELECT 'Ella Highlands','Slow down among emerald tea fields, cloud forests and storied railway bridges in Sri Lanka’s cool central hills.','assets/gallery-5.jpg',(SELECT category_id FROM categories WHERE category_name='Highlands'),'Uva Province','Nine Arch Bridge, tea trails, Little Adam’s Peak','assets/gallery-5.jpg','assets/gallery-6.jpg','assets/gallery-7.jpg','assets/gallery-8.jpg' WHERE NOT EXISTS(SELECT 1 FROM destinations WHERE name='Ella Highlands');
INSERT INTO destinations(name,description,image,category_id,location,highlights,gallery_image1,gallery_image2,gallery_image3,gallery_image4)
SELECT 'Yala Wild Coast','Follow leopard tracks through thorn forest, watch elephants gather at hidden waterholes and end the day beside the Indian Ocean.','assets/gallery-9.jpg',(SELECT category_id FROM categories WHERE category_name='Wildlife'),'Southern Province','Private safari, birdlife, wild coastline','assets/gallery-9.jpg','assets/gallery-10.jpg','assets/gallery-11.jpg','assets/gallery-12.jpg' WHERE NOT EXISTS(SELECT 1 FROM destinations WHERE name='Yala Wild Coast');
INSERT INTO packages(name,description,image,duration,destinations,inclusions,exclusions,gallery_image1,gallery_image2,gallery_image3,gallery_image4)
SELECT 'The Island Edit','A beautifully paced first journey through ancient capitals, tea country, wildlife and the south coast.','assets/packages.jpg','10 days / 9 nights','Sigiriya · Kandy · Ella · Yala · Galle','Boutique stays\nPrivate transport\nLocal guides\nDaily breakfast\nTwo signature experiences','Flights\nTravel insurance\nPersonal expenses','assets/gallery-1.jpg','assets/gallery-5.jpg','assets/gallery-9.jpg','assets/about-6.jpg' WHERE NOT EXISTS(SELECT 1 FROM packages WHERE name='The Island Edit');
INSERT INTO packages(name,description,image,duration,destinations,inclusions,exclusions,gallery_image1,gallery_image2,gallery_image3,gallery_image4)
SELECT 'Wild & Slow','An immersive nature-led escape pairing cloud-forest walks, ethical wildlife encounters and quiet coastal days.','assets/about-2.jpg','7 days / 6 nights','Ella · Yala · Tangalle','Eco stays\nPrivate naturalist\nSafari drive\nGuided hikes\nDaily breakfast','Flights\nTravel insurance','assets/about-2.jpg','assets/gallery-7.jpg','assets/gallery-10.jpg','assets/contact.jpg' WHERE NOT EXISTS(SELECT 1 FROM packages WHERE name='Wild & Slow');
INSERT INTO packages(name,description,image,duration,destinations,inclusions,exclusions,gallery_image1,gallery_image2,gallery_image3,gallery_image4)
SELECT 'Ceylon in Style','Heritage hotels, private dining and unhurried access to Sri Lanka’s most compelling cultural landscapes.','assets/about-4.jpg','12 days / 11 nights','Colombo · Cultural Triangle · Tea Country · Galle','Luxury stays\nPrivate chauffeur-guide\nCurated dining\nAll breakfasts','Flights\nTravel insurance\nSelected lunches','assets/about-4.jpg','assets/gallery-2.jpg','assets/about-5.jpg','assets/gallery-12.jpg' WHERE NOT EXISTS(SELECT 1 FROM packages WHERE name='Ceylon in Style');
INSERT INTO activities(name,description,image,activity_type_id,category,difficulty,inclusions)
SELECT 'Dawn Safari','Enter Yala at first light with a specialist naturalist and track leopards, elephants and endemic birds.','assets/gallery-10.jpg',(SELECT activity_type_id FROM activity_types WHERE activity_type_name='Wildlife'),'Wildlife','Easy','Private jeep\nNaturalist guide\nRefreshments' WHERE NOT EXISTS(SELECT 1 FROM activities WHERE name='Dawn Safari');
INSERT INTO activities(name,description,image,activity_type_id,category,difficulty,inclusions)
SELECT 'Tea Country Trail','Walk between working estates, meet a tea maker and share a garden lunch above the clouds.','assets/gallery-6.jpg',(SELECT activity_type_id FROM activity_types WHERE activity_type_name='Hiking'),'Hiking','Moderate','Local guide\nTea tasting\nEstate lunch' WHERE NOT EXISTS(SELECT 1 FROM activities WHERE name='Tea Country Trail');
INSERT INTO activities(name,description,image,activity_type_id,category,difficulty,inclusions)
SELECT 'Village Table','Cook fragrant Sri Lankan curries with a local family and discover the stories behind every spice.','assets/about-3.jpg',(SELECT activity_type_id FROM activity_types WHERE activity_type_name='Culture'),'Culture','Easy','Market visit\nCooking session\nShared lunch' WHERE NOT EXISTS(SELECT 1 FROM activities WHERE name='Village Table');
