USE eco_tourism;
START TRANSACTION;
INSERT INTO destinations (name,location,description,image,category_id,highlights,gallery_image1,gallery_image2,gallery_image3,gallery_image4) SELECT 'Idalgashinna','Uva Province','Discover Idalgashinna through its hill-country scenery, railway views and quiet green landscapes.','assets/destinations/user/idalgashinna/01-main.jpg','2','Hill-country scenery
Railway views
Green landscapes','assets/destinations/user/idalgashinna/02-gallery.jpg','assets/destinations/user/idalgashinna/03-gallery.jpeg','assets/destinations/user/idalgashinna/04-gallery.jpg','' WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE name='Idalgashinna');
UPDATE destinations SET image='assets/destinations/user/idalgashinna/01-main.jpg',gallery_image1='assets/destinations/user/idalgashinna/02-gallery.jpg',gallery_image2='assets/destinations/user/idalgashinna/03-gallery.jpeg',gallery_image3='assets/destinations/user/idalgashinna/04-gallery.jpg',gallery_image4='' WHERE name='Idalgashinna';
INSERT INTO destinations (name,location,description,image,category_id,highlights,gallery_image1,gallery_image2,gallery_image3,gallery_image4) SELECT 'Kabaragala','Sri Lanka','Explore the mountain scenery of Kabaragala, with open ridges and sweeping views across the surrounding hills.','assets/destinations/user/kabaragala/01-main.jpeg','2','Mountain scenery
Ridge views
Nature photography','assets/destinations/user/kabaragala/02-gallery.jpg','assets/destinations/user/kabaragala/03-gallery.jpeg','assets/destinations/user/kabaragala/04-gallery.jpeg','' WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE name='Kabaragala');
UPDATE destinations SET image='assets/destinations/user/kabaragala/01-main.jpeg',gallery_image1='assets/destinations/user/kabaragala/02-gallery.jpg',gallery_image2='assets/destinations/user/kabaragala/03-gallery.jpeg',gallery_image3='assets/destinations/user/kabaragala/04-gallery.jpeg',gallery_image4='' WHERE name='Kabaragala';
INSERT INTO destinations (name,location,description,image,category_id,highlights,gallery_image1,gallery_image2,gallery_image3,gallery_image4) SELECT 'Kohombagala','Sri Lanka','Discover Kohombagala and explore its scenery through our destination photo gallery.','assets/destinations/user/kohombagala/01-main.jpg','2','Local scenery
Nature photography','assets/destinations/user/kohombagala/02-gallery.avif','assets/destinations/user/kohombagala/03-gallery.jpeg','assets/destinations/user/kohombagala/04-gallery.jpeg','' WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE name='Kohombagala');
UPDATE destinations SET image='assets/destinations/user/kohombagala/01-main.jpg',gallery_image1='assets/destinations/user/kohombagala/02-gallery.avif',gallery_image2='assets/destinations/user/kohombagala/03-gallery.jpeg',gallery_image3='assets/destinations/user/kohombagala/04-gallery.jpeg',gallery_image4='' WHERE name='Kohombagala';
INSERT INTO destinations (name,location,description,image,category_id,highlights,gallery_image1,gallery_image2,gallery_image3,gallery_image4) SELECT 'Peacock Hill','Pussellawa, Central Province','Take in the mountain landscape from Peacock Hill near Pussellawa, with views across the Kotmale reservoir and surrounding hill country.','assets/destinations/user/peacock-hill/01-main.jpg','2','Mountain viewpoint
Kotmale reservoir views
Hill-country scenery','assets/destinations/user/peacock-hill/02-gallery.jpeg','assets/destinations/user/peacock-hill/03-gallery.jpg','assets/destinations/user/peacock-hill/04-gallery.jpg','assets/destinations/user/peacock-hill/05-gallery.jpg' WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE name='Peacock Hill');
UPDATE destinations SET image='assets/destinations/user/peacock-hill/01-main.jpg',gallery_image1='assets/destinations/user/peacock-hill/02-gallery.jpeg',gallery_image2='assets/destinations/user/peacock-hill/03-gallery.jpg',gallery_image3='assets/destinations/user/peacock-hill/04-gallery.jpg',gallery_image4='assets/destinations/user/peacock-hill/05-gallery.jpg' WHERE name='Peacock Hill';
INSERT INTO destinations (name,location,description,image,category_id,highlights,gallery_image1,gallery_image2,gallery_image3,gallery_image4) SELECT 'Seven Virgin Mountains','Sri Lanka','Discover the dramatic silhouettes and green mountain landscapes of the Seven Virgin Mountains.','assets/destinations/user/seven-virgin-mountains/01-main.jpg','2','Mountain landscapes
Scenic views
Nature photography','assets/destinations/user/seven-virgin-mountains/02-gallery.jpeg','assets/destinations/user/seven-virgin-mountains/03-gallery.jpeg','assets/destinations/user/seven-virgin-mountains/04-gallery.jpeg','assets/destinations/user/seven-virgin-mountains/05-gallery.jpeg' WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE name='Seven Virgin Mountains');
UPDATE destinations SET image='assets/destinations/user/seven-virgin-mountains/01-main.jpg',gallery_image1='assets/destinations/user/seven-virgin-mountains/02-gallery.jpeg',gallery_image2='assets/destinations/user/seven-virgin-mountains/03-gallery.jpeg',gallery_image3='assets/destinations/user/seven-virgin-mountains/04-gallery.jpeg',gallery_image4='assets/destinations/user/seven-virgin-mountains/05-gallery.jpeg' WHERE name='Seven Virgin Mountains';
INSERT INTO destinations (name,location,description,image,category_id,highlights,gallery_image1,gallery_image2,gallery_image3,gallery_image4) SELECT 'Thotupola Kanda','Horton Plains, Central Province','Explore the mountain forest landscape of Thotupola Kanda in Horton Plains, surrounded by the cool scenery of Sri Lanka''s central highlands.','assets/destinations/user/thotupola-kanda/01-main.webp','2','Mountain forest
Horton Plains landscape
Highland scenery','assets/destinations/user/thotupola-kanda/02-gallery.webp','assets/destinations/user/thotupola-kanda/03-gallery.jpeg','','' WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE name='Thotupola Kanda');
UPDATE destinations SET image='assets/destinations/user/thotupola-kanda/01-main.webp',gallery_image1='assets/destinations/user/thotupola-kanda/02-gallery.webp',gallery_image2='assets/destinations/user/thotupola-kanda/03-gallery.jpeg',gallery_image3='',gallery_image4='' WHERE name='Thotupola Kanda';
INSERT INTO destinations (name,location,description,image,category_id,highlights,gallery_image1,gallery_image2,gallery_image3,gallery_image4) SELECT 'Uragala','Sri Lanka','Discover Uragala and explore its scenery through our destination photo gallery.','assets/destinations/user/uragala/01-main.webp','2','Local scenery
Nature photography','assets/destinations/user/uragala/02-gallery.webp','assets/destinations/user/uragala/03-gallery.webp','assets/destinations/user/uragala/04-gallery.webp','assets/destinations/user/uragala/05-gallery.webp' WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE name='Uragala');
UPDATE destinations SET image='assets/destinations/user/uragala/01-main.webp',gallery_image1='assets/destinations/user/uragala/02-gallery.webp',gallery_image2='assets/destinations/user/uragala/03-gallery.webp',gallery_image3='assets/destinations/user/uragala/04-gallery.webp',gallery_image4='assets/destinations/user/uragala/05-gallery.webp' WHERE name='Uragala';
COMMIT;
