<?php
session_start();require_once '../config/database.php';require_once '../config/human-chat.php';
if(!isset($_SESSION['admin_id'])){header('Location: login.php');exit;}
$db=(new Database())->getConnection();ensureHumanChatTables($db);include 'includes/admin_header.php';
?>
<style>
.live-chat-app{height:calc(100vh - 130px);min-height:620px;display:grid;grid-template-columns:340px 1fr;background:#fff;border:1px solid #dfe5e1;border-radius:22px;overflow:hidden}.chat-inbox{border-right:1px solid #e3e8e5;background:#f6f7f3}.chat-inbox-head{padding:22px;border-bottom:1px solid #dfe5e1}.chat-inbox-head h1{font-size:24px}.chat-inbox-head p{font-size:12px;color:#718078}.chat-session-list{height:calc(100% - 90px);overflow:auto}.chat-session{width:100%;padding:16px 18px;border:0;border-bottom:1px solid #e2e7e4;background:transparent;text-align:left;cursor:pointer}.chat-session:hover,.chat-session.active{background:#eaf2d5}.chat-session strong{display:flex;justify-content:space-between;color:#183d31}.chat-session strong i{font-style:normal;font-size:9px;text-transform:uppercase;color:#9a632e}.chat-session p{margin:5px 0;color:#66766e;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.chat-session small{font-size:10px;color:#91a099}.chat-workspace{display:flex;flex-direction:column;min-width:0}.chat-workspace-head{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:18px 22px;border-bottom:1px solid #e3e8e5}.agent-controls{display:flex;gap:8px}.agent-controls input{border:1px solid #d7dfda;border-radius:999px;padding:10px 14px}.agent-controls button,.chat-composer button{border:0;border-radius:999px;background:#173f32;color:#fff;padding:10px 18px;font-weight:700}.chat-thread{flex:1;overflow:auto;padding:24px;background:#f8f7f1}.admin-bubble{max-width:72%;margin:0 0 14px;padding:12px 15px;border-radius:17px;background:#fff;box-shadow:0 3px 12px #173f320d}.admin-bubble.agent{margin-left:auto;background:#dcef87}.admin-bubble.system{max-width:100%;text-align:center;background:transparent;box-shadow:none;color:#7d8a84;font-size:11px}.admin-bubble strong{display:block;font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#27664d}.admin-bubble p{margin:3px 0;white-space:pre-wrap}.chat-composer{display:flex;gap:10px;padding:16px 20px;border-top:1px solid #e3e8e5}.chat-composer textarea{flex:1;resize:none;border:1px solid #d7dfda;border-radius:15px;padding:12px;outline:none}.empty-chat{margin:auto;text-align:center;color:#819088}.empty-chat i{font-size:45px;color:#c4d4cb}@media(max-width:800px){.live-chat-app{grid-template-columns:1fr;height:auto}.chat-inbox{max-height:310px}.chat-workspace{min-height:600px}.chat-workspace-head{align-items:flex-start;flex-direction:column}.admin-bubble{max-width:88%}}
</style>
<div class="live-chat-app">
 <aside class="chat-inbox"><div class="chat-inbox-head"><h1>Live conversations</h1><p>Visitors waiting for a real travel specialist</p></div><div class="chat-session-list" id="session-list"></div></aside>
 <section class="chat-workspace"><header class="chat-workspace-head"><div><strong id="visitor-title">Select a conversation</strong><p id="chat-status" class="text-xs text-gray-500"></p></div><div class="agent-controls"><input id="agent-name" value="<?= htmlspecialchars($_SESSION['admin_username']) ?>" maxlength="80" placeholder="Your display name"><button id="join-chat" type="button" disabled>Join as this name</button><button id="close-chat" type="button" disabled>Close</button></div></header><div class="chat-thread" id="admin-thread"><div class="empty-chat"><i class="fas fa-comments"></i><p>Choose a visitor to begin.</p></div></div><form class="chat-composer" id="admin-chat-form"><textarea id="admin-message" maxlength="2000" rows="2" placeholder="Reply to the visitor…" disabled></textarea><button type="submit" disabled>Send</button></form></section>
</div>
<script>
(()=>{const api='human-chat-api.php',list=document.querySelector('#session-list'),thread=document.querySelector('#admin-thread'),title=document.querySelector('#visitor-title'),status=document.querySelector('#chat-status'),name=document.querySelector('#agent-name'),join=document.querySelector('#join-chat'),close=document.querySelector('#close-chat'),form=document.querySelector('#admin-chat-form'),input=document.querySelector('#admin-message');let active=0,last=0;
const call=async data=>{const r=await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j};
const esc=s=>{const d=document.createElement('div');d.textContent=s;return d.innerHTML};
async function refreshList(){try{const d=await call({action:'list'});list.innerHTML=d.sessions.map(s=>`<button class="chat-session ${+s.id===active?'active':''}" data-id="${s.id}" data-name="${esc(s.visitor_name)}"><strong>${esc(s.visitor_name)}<i>${esc(s.status)}</i></strong><p>${esc(s.last_message||'New conversation')}</p><small>${esc(s.last_activity)}</small></button>`).join('')||'<p class="p-6 text-sm text-gray-500">No conversations yet.</p>';list.querySelectorAll('button').forEach(b=>b.onclick=()=>select(+b.dataset.id,b.dataset.name))}catch(e){}}
function select(id,visitor){active=id;last=0;thread.innerHTML='';title.textContent=visitor;join.disabled=close.disabled=input.disabled=form.querySelector('button').disabled=false;messages();refreshList()}
function add(m){const el=document.createElement('div');el.className=`admin-bubble ${m.sender}`;el.innerHTML=`<strong>${esc(m.sender_name)}</strong><p>${esc(m.message)}</p><small>${esc(m.created_at)}</small>`;thread.append(el);thread.scrollTop=thread.scrollHeight;last=Math.max(last,+m.id)}
async function messages(){if(!active)return;try{const d=await call({action:'messages',session_id:active,after:last});d.messages.forEach(add);status.textContent=`${d.session.status}${d.session.agent_name?' · '+d.session.agent_name:''}`}catch(e){}}
join.onclick=async()=>{if(!active)return;await call({action:'join',session_id:active,agent_name:name.value});messages();refreshList()};close.onclick=async()=>{if(!active)return;await call({action:'close',session_id:active});status.textContent='closed';refreshList()};form.onsubmit=async e=>{e.preventDefault();if(!active||!input.value.trim())return;await call({action:'send',session_id:active,agent_name:name.value,message:input.value.trim()});input.value='';messages();refreshList()};refreshList();setInterval(()=>{refreshList();messages()},3000)})();
</script>
<?php include 'includes/admin_footer.php'; ?>
