<?php
declare(strict_types=1);session_start();header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
if(!isset($_SESSION['admin_id'])){http_response_code(403);echo json_encode(['error'=>'Admin login required.']);exit;}
require_once '../config/database.php';require_once '../config/human-chat.php';$db=(new Database())->getConnection();ensureHumanChatTables($db);
$input=json_decode((string)file_get_contents('php://input'),true) ?: [];$action=(string)($input['action']??'');
function adminOut(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if($action==='list'){$q=$db->query("SELECT s.*, (SELECT message FROM human_chat_messages m WHERE m.session_id=s.id ORDER BY m.id DESC LIMIT 1) last_message, (SELECT COUNT(*) FROM human_chat_messages m WHERE m.session_id=s.id) message_count FROM human_chat_sessions s ORDER BY FIELD(status,'waiting','active','closed'),last_activity DESC LIMIT 100");adminOut(['sessions'=>$q->fetchAll(PDO::FETCH_ASSOC)]);}
$id=max(0,(int)($input['session_id']??0));$s=$db->prepare('SELECT * FROM human_chat_sessions WHERE id=?');$s->execute([$id]);$session=$s->fetch(PDO::FETCH_ASSOC);if(!$session)adminOut(['error'=>'Conversation not found.'],404);
if($action==='join'){$name=cleanChatName((string)($input['agent_name']??''),(string)$_SESSION['admin_username']);$db->prepare("UPDATE human_chat_sessions SET status='active',agent_name=?,last_activity=NOW() WHERE id=?")->execute([$name,$id]);$db->prepare("INSERT INTO human_chat_messages(session_id,sender,sender_name,message) VALUES(?,'system','Serendib Pathways',?)")->execute([$id,$name.' joined the conversation.']);adminOut(['success'=>true,'agent_name'=>$name]);}
if($action==='send'){$name=cleanChatName((string)($input['agent_name']??$session['agent_name']),(string)$_SESSION['admin_username']);$message=trim((string)($input['message']??''));if($message===''||mb_strlen($message)>2000)adminOut(['error'=>'Enter a message under 2,000 characters.'],422);$db->prepare("UPDATE human_chat_sessions SET status='active',agent_name=?,last_activity=NOW() WHERE id=?")->execute([$name,$id]);$db->prepare("INSERT INTO human_chat_messages(session_id,sender,sender_name,message) VALUES(?,'agent',?,?)")->execute([$id,$name,$message]);adminOut(['success'=>true]);}
if($action==='messages'){$after=max(0,(int)($input['after']??0));$q=$db->prepare('SELECT id,sender,sender_name,message,created_at FROM human_chat_messages WHERE session_id=? AND id>? ORDER BY id');$q->execute([$id,$after]);adminOut(['messages'=>$q->fetchAll(PDO::FETCH_ASSOC),'session'=>$session]);}
if($action==='close'){$db->prepare("UPDATE human_chat_sessions SET status='closed',last_activity=NOW() WHERE id=?")->execute([$id]);adminOut(['success'=>true]);}
adminOut(['error'=>'Unsupported action.'],400);
