</main><section class="prefooter"><div><span class="eyebrow">YOUR STORY STARTS HERE</span><h2>Ready to see Sri Lanka<br><em>differently?</em></h2></div><a href="contact.php" class="circle-link" aria-label="Plan your journey"><span>Plan your<br>journey</span><i class="fa-solid fa-arrow-right"></i></a></section>
<footer class="site-footer"><div class="footer-grid"><div><a class="brand brand-light" href="index.php"><span class="brand-scene footer-scene"><img src="assets/serendib-pathways-transparent.png" alt=""></span><span class="brand-name footer-brand-name"><strong>Serendib</strong><small>Pathways</small></span></a><p>Rare places. Real people.<br>Remarkable Sri Lanka.</p></div><div><h3>Explore</h3><a href="destinations.php">Destinations</a><a href="packages.php">Journeys</a><a href="activities.php">Experiences</a><a href="about.php">Our story</a><a href="photo-credits.php">Photo credits</a></div><div><h3>Connect</h3><a href="mailto:hello@serendibpathways.com">hello@serendibpathways.com</a><a href="tel:+94771234567">+94 77 123 4567</a></div></div><div class="footer-bottom"><span>© <?= date('Y') ?> Serendib Pathways. All rights reserved.</span><span>Made with care in Sri Lanka</span></div></footer>
<button class="ai-chat-toggle" id="ai-chat-toggle" type="button" aria-label="Open AI travel assistant" aria-expanded="false" aria-controls="ai-chat-panel"><i class="fa-solid fa-comment-dots"></i></button>
<link href="assets/css/human-chat.css?v=1" rel="stylesheet">
<section class="ai-chat-panel" id="ai-chat-panel" aria-label="AI travel assistant" aria-hidden="true">
    <header class="ai-chat-header"><div><span class="ai-chat-status"></span><strong id="chat-assistant-name">Serendib Pathways Assistant</strong><small id="chat-assistant-status">Powered by Gemini</small></div><button class="human-chat-start" id="human-chat-start" type="button"><i class="fa-solid fa-headset"></i> Talk to a person</button><button id="ai-chat-close" type="button" aria-label="Close chat"><i class="fa-solid fa-xmark"></i></button></header>
    <div class="human-chat-banner" id="human-chat-banner" hidden><span class="human-chat-dot"></span><span id="human-chat-state">Waiting for a travel specialist…</span><button id="human-chat-exit" type="button">Return to Nila</button></div>
    <div class="ai-chat-messages" id="ai-chat-messages" aria-live="polite"><div class="ai-message assistant">Ayubowan! I’m your AI travel assistant. Ask me anything about Sri Lanka or planning your journey.</div></div>
    <form class="ai-chat-form" id="ai-chat-form"><label class="sr-only" for="ai-chat-input">Your message</label><textarea id="ai-chat-input" maxlength="2000" rows="1" placeholder="Ask me anything…" required></textarea><button type="submit" aria-label="Send message"><i class="fa-solid fa-paper-plane"></i></button></form>
    <p class="ai-chat-note">AI responses can be inaccurate. Confirm important travel details.</p>
</section>
<script src="assets/js/script.js?v=8"></script></body></html>
